name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 6:43
    - cron: "43 6 * * *"

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"
  PYTHON_LATEST: "3.11"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_LATEST }}
      - uses: pre-commit/action@v3.0.0

  list:
    runs-on: ubuntu-latest
    outputs:
      noxenvs: ${{ steps.noxenvs-matrix.outputs.noxenvs }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up nox
        uses: wntrblm/nox@2022.11.21
      - id: noxenvs-matrix
        run: |
          echo >>$GITHUB_OUTPUT noxenvs=$(
            nox --list-sessions |
            grep '^* ' |
            cut -d ' ' -f 2- |
            jq --raw-input --slurp 'split("\n") | map(select(. != ""))'
          )

  ci:
    needs: list
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        noxenv: ${{ fromJson(needs.list.outputs.noxenvs) }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y libenchant-2-dev
        if: runner.os == 'Linux'
      - name: Install dependencies
        run: brew install enchant
        if: runner.os == 'macOS'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_LATEST }}
      - name: Set up nox
        uses: wntrblm/nox@2022.11.21
      - name: Run nox
        run: nox -s "${{ matrix.noxenv }}"

  packaging:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_LATEST }}
      - name: Install dependencies
        run: python -m pip install build
      - name: Create packages
        run: python -m build .
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Publish the package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}
      - name: Create a Release
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
